# Generated by Django 6.0.3 on 2026-04-10 17:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'verbose_name': "Yig'ilish ", 'verbose_name_plural': "Yig'lishlar"},
        ),
        migrations.AlterModelOptions(
            name='meetingattendance',
            options={'verbose_name': "Yig'ilishga qatnashish ", 'verbose_name_plural': "Yig'ilishga qatnashishlar"},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Loyiha ', 'verbose_name_plural': 'Loyihalar'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Vazifa ', 'verbose_name_plural': 'Vazifalar'},
        ),
        migrations.AlterModelOptions(
            name='taskattachment',
            options={'verbose_name': 'Vazifa fayli ', 'verbose_name_plural': 'Vazifa fayllari'},
        ),
        migrations.AddField(
            model_name='task',
            name='penalty_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Jarima foizi (%)'),
        ),
        migrations.AddField(
            model_name='task',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Rad etish sababi'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.TextField(verbose_name='Tavfsifi'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='duration_minutes',
            field=models.PositiveIntegerField(verbose_name='Davomiyligi'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faolmi?'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Tugatildimi?'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='link',
            field=models.URLField(verbose_name='Havolasi'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Tashkilotchi'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(related_name='meeting_participants', through='projects.MeetingAttendance', to=settings.AUTH_USER_MODEL, verbose_name='Qatnashuvchilar'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='projects.project', verbose_name='Loyiha'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.DateTimeField(verbose_name='Boshlanish vaqti'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='meetingattendance',
            name='absence_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Sababi'),
        ),
        migrations.AlterField(
            model_name='meetingattendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='meetingattendance',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faolmi?'),
        ),
        migrations.AlterField(
            model_name='meetingattendance',
            name='is_attended',
            field=models.BooleanField(default=True, verbose_name='Qatnashdimi?'),
        ),
        migrations.AlterField(
            model_name='meetingattendance',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='projects.meeting', verbose_name='Uchrashuv'),
        ),
        migrations.AlterField(
            model_name='meetingattendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='meetingattendance',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(verbose_name='Muddati'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Tavsifi'),
        ),
        migrations.AlterField(
            model_name='project',
            name='employees',
            field=models.ManyToManyField(limit_choices_to={'role': 'employee'}, related_name='employee_projects', to=settings.AUTH_USER_MODEL, verbose_name='Xodimlar'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faolmi?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'role': 'manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_projects', to=settings.AUTH_USER_MODEL, verbose_name='Menejer'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Boshlanish sanasi'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planning', 'Rejalashtirilmoqda'), ('active', 'Faol'), ('overdue', "Muddati o'tgan"), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], db_index=True, default='planning', max_length=20, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='project',
            name='testers',
            field=models.ManyToManyField(related_name='tester_projects', to=settings.AUTH_USER_MODEL, verbose_name='Sinovchilar'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='task',
            name='actual_hours',
            field=models.FloatField(default=0.0, verbose_name='Haqiqiy ish vaqti'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'employee'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Topshiruvchi'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(db_index=True, verbose_name='Muddati'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(verbose_name='Tavsifi'),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_hours',
            field=models.FloatField(default=0.0, verbose_name='Taxminiy soatlar'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faolmi?'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Past'), ('medium', 'Oʻrta'), ('high', 'Yuqori'), ('critical', 'Kritik')], db_index=True, default='medium', max_length=20, verbose_name='Darajasi'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='projects.project', verbose_name='Loyiha'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reopened_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Qaytishlar soni'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'Kutilmoqda'), ('in_progress', 'Jarayonda'), ('overdue', "Muddati o'tgan"), ('done', 'Bajarildi'), ('production', 'Ishga tushirildi'), ('checked', 'Tekshirildi'), ('rejected', 'Rad etildi')], db_index=True, default='todo', max_length=20, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Vazifa narxi'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('bug', 'Xatolik (Bug)'), ('extra', 'Qoʻshimcha'), ('feature', 'Yangi funksiya'), ('research', 'Tadqiqot/Oʻrganish')], db_index=True, default='feature', max_length=20, verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=models.FileField(upload_to='task_files/', verbose_name='Fayl'),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faolmi?'),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='projects.task', verbose_name='Vazifa'),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti'),
        ),
    ]
