# Generated by Django 6.0.3 on 2026-04-11 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_meeting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='actual_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Haqiqiy ish vaqti'),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Taxminiy soatlar'),
        ),
    ]
