# Generated by Django 6.0.3 on 2026-04-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_task_actual_hours_alter_task_estimated_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='actual_hours',
        ),
        migrations.RemoveField(
            model_name='task',
            name='estimated_hours',
        ),
        migrations.AddField(
            model_name='task',
            name='actual_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Haqiqiy ish vaqti (daqiqa)'),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Taxminiy vaqt (daqiqa)'),
        ),
    ]
