# Generated by Django 6.0.3 on 2026-04-11 05:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_task_actual_hours_remove_task_estimated_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='penalty_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Kechikkanlik uchun jarima foizi (%)'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Menejer bonusi (Loyiha uchun)'),
        ),
    ]
