# Generated by Django 6.0.3 on 2026-04-11 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_penalty_percentage_project_project_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='penalty_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Jarima foizi (%)'),
        ),
    ]
