# Generated by Django 6.0.3 on 2026-04-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_meeting_penalty_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
