# Generated by Django 6.0.3 on 2026-04-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_task_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='uid',
            field=models.CharField(default=0, editable=False, max_length=7, unique=True, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='uid',
            field=models.CharField(default=11, editable=False, max_length=7, unique=True, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
