# Generated by Django 6.0.3 on 2026-04-10 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'ordering': ['title'], 'verbose_name': 'Xarajatlar toifasi ', 'verbose_name_plural': 'Xarajatlar toifalari'},
        ),
        migrations.AlterModelOptions(
            name='expenserequest',
            options={'ordering': ['-created_at'], 'verbose_name': "Xarajat so'rovi ", 'verbose_name_plural': "Xarajat so'rovlari"},
        ),
        migrations.AlterModelOptions(
            name='ledger',
            options={'ordering': ['-created_at'], 'verbose_name': 'Arxiv ', 'verbose_name_plural': 'Arxivlar'},
        ),
        migrations.AlterModelOptions(
            name='payroll',
            options={'verbose_name': 'Ish haqi ', 'verbose_name_plural': 'Ish haqlari'},
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faolmi?'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='expenserequest',
            name='accountant',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'accountant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Hisobchi'),
        ),
        migrations.AlterField(
            model_name='expenserequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Miqdori'),
        ),
        migrations.AlterField(
            model_name='expenserequest',
            name='card_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Karta raqami'),
        ),
        migrations.AlterField(
            model_name='expenserequest',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqti'),
        ),
        migrations.AlterField(
            model_name='expenserequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='expenserequest',
            name='expense_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_requests', to='finance.expensecategory', verbose_name='Xarajat kategoriyasi'),
        ),
        migrations.AlterField(
            model_name='expenserequest',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faolmi?'),
        ),
        migrations.AlterField(
            model_name='expenserequest',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="To'langan vaqti"),
        ),
        migrations.AlterField(
            model_name='expenserequest',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Naqd pul'), ('card', 'Karta')], default='card', max_length=10, verbose_name="To'lov turi"),
        ),
        migrations.AlterField(
            model_name='expenserequest',
            name='reason',
            field=models.TextField(verbose_name='Sababi'),
        ),
        migrations.AlterField(
            model_name='expenserequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('paid', "To'landi"), ('confirmed', 'Tasdiqlandi')], default='pending', max_length=20, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='expenserequest',
            name='type',
            field=models.CharField(choices=[('withdrawal', 'Pulni yechib olish'), ('company', 'Kompaniya uchun'), ('other', 'Boshqa')], default='withdrawal', max_length=20, verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='expenserequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='expenserequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Miqdori'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.expenserequest', verbose_name='Xarajat'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faolmi?'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='payroll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.payroll', verbose_name='Ish haqi'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='transaction_type',
            field=models.CharField(choices=[('debit', 'Chiqim'), ('credit', 'Kirim')], max_length=10, verbose_name='Tranzaksiya turi'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='bug_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Xatolar'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='deadline_missed',
            field=models.PositiveIntegerField(default=0, verbose_name="Muddatdan o'tkazib yuborilganlar"),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='fixed_salary',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Oylik maosh'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faolmi?'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='kpi_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='KPI bonusi'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='month',
            field=models.DateField(verbose_name='Oy'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Jarima miqdori'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='tasks_completed',
            field=models.PositiveIntegerField(default=0, verbose_name='Bajarilgan vazifalar'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Jami miqdori'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrolls', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
    ]
