# Generated by Django 6.0.3 on 2026-04-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Bosh administrator'), ('admin', 'Administrator'), ('manager', 'Menejer'), ('employee', 'Xodim'), ('auditor', 'Nazoratchi'), ('accountant', 'Hisobchi')], db_index=True, default='employee', max_length=20, verbose_name='Roli'),
        ),
    ]
