# Generated by Django 6.0.3 on 2026-04-10 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'verbose_name': 'Tarix yozuvi ', 'verbose_name_plural': 'Tarix yozuvlari'},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('confirm', 'Confirm')], max_length=50, verbose_name='Harakati'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzili'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faolmi?'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='new_values',
            field=models.JSONField(blank=True, null=True, verbose_name='Yangi qiymati'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='old_values',
            field=models.JSONField(blank=True, null=True, verbose_name='Eski qiymati'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='record_id',
            field=models.PositiveIntegerField(verbose_name='Yozuv raqami'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='table_name',
            field=models.CharField(max_length=50, verbose_name='Jadval nomi'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vaqti'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
    ]
